plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = mod_version
group = mod_group_id

base.archivesName = "${mod_id}-neoforge-${minecraft_version}"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
    maven { name = 'NeoForged';  url = 'https://maven.neoforged.net/releases' }
    maven { name = 'Create';     url = 'https://maven.createmod.net' }
    maven { name = 'tterrag';    url = 'https://maven.tterrag.com/' }
    maven { name = 'ModMaven';   url = 'https://modmaven.dev' }
    flatDir { dirs 'libs' }
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client { client() }
        server { server() }
        data {
            clientData()
            programArguments.addAll '--mod', mod_id,
                    '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    from(rootProject.file('LICENSE.md'))
    from(rootProject.file('THIRD-PARTY.md'))

    exclude '**/*.bak', '**/*.orig', '**/*.tmp'

    def replacements = [
        mod_id                  : mod_id,
        mod_name                : mod_name,
        mod_license             : mod_license,
        mod_version             : mod_version,
        mod_authors             : mod_authors,
        mod_description         : mod_description,
        minecraft_version       : minecraft_version,
        minecraft_version_range : minecraft_version_range,
        neo_version             : neo_version,
        neo_version_range       : neo_version_range,
        loader_version_range    : loader_version_range,
        create_version_range    : create_version_range,
        coasters_version_range  : coasters_version_range,
    ]
    inputs.properties replacements
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replacements
    }
}

jar {
    manifest {
        attributes([
            'Specification-Title'   : mod_id,
            'Specification-Vendor'  : mod_authors,
            'Specification-Version' : '1',
            'Implementation-Title'  : project.name,
            'Implementation-Version': project.jar.archiveVersion,
            'Implementation-Vendor' : mod_authors,
        ])
    }
}
