org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.248
neo_version_range=[21.1.0,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

create_version_range=[6.0.0,7.0.0)
coasters_version_range=[0.1.2,0.2.0)

mod_id=coasters_extras
mod_name=Create: Coasters Extras
mod_license=Read attached LICENSE.md
mod_version=1.2
mod_group_id=dev.notzyvex.coasters_extras
mod_authors=NotZyvex
mod_description=Adds more balloon colours and new coaster track types to Create: Coasters Simulated.
