package dev.notzyvex.coasters_extras.track;

public enum TrackVariant {
    OAK      ("oak",       "Oak"),
    SPRUCE   ("spruce",    "Spruce"),
    BIRCH    ("birch",     "Birch"),
    JUNGLE   ("jungle",    "Jungle"),
    ACACIA   ("acacia",    "Acacia"),
    DARK_OAK ("dark_oak",  "Dark Oak"),
    MANGROVE ("mangrove",  "Mangrove"),
    CHERRY   ("cherry",    "Cherry"),
    BAMBOO   ("bamboo",    "Bamboo"),
    CRIMSON  ("crimson",   "Crimson"),
    WARPED   ("warped",    "Warped"),
    STONE    ("stone",     "Stone"),
    DEEPSLATE("deepslate", "Deepslate"),
    ANDESITE ("andesite",  "Andesite"),
    GRANITE  ("granite",   "Granite"),
    DIORITE  ("diorite",   "Diorite"),
    RUST     ("rust",      "Rusted"),
    RAINBOW  ("rainbow",   "Rainbow"),
    ROSE_QUARTZ("rose_quartz", "Rose Quartz"),
    BRASS("brass", "Brass"),
    COPPER("copper", "Copper"),
    ZINC("zinc", "Zinc"),

    WHITE_WOOL            ("white_wool", "White Wool"),
    LIGHT_GRAY_WOOL       ("light_gray_wool", "Light Gray Wool"),
    GRAY_WOOL             ("gray_wool", "Gray Wool"),
    BLACK_WOOL            ("black_wool", "Black Wool"),
    BROWN_WOOL            ("brown_wool", "Brown Wool"),
    RED_WOOL              ("red_wool", "Red Wool"),
    ORANGE_WOOL           ("orange_wool", "Orange Wool"),
    YELLOW_WOOL           ("yellow_wool", "Yellow Wool"),
    LIME_WOOL             ("lime_wool", "Lime Wool"),
    GREEN_WOOL            ("green_wool", "Green Wool"),
    CYAN_WOOL             ("cyan_wool", "Cyan Wool"),
    LIGHT_BLUE_WOOL       ("light_blue_wool", "Light Blue Wool"),
    BLUE_WOOL             ("blue_wool", "Blue Wool"),
    PURPLE_WOOL           ("purple_wool", "Purple Wool"),
    MAGENTA_WOOL          ("magenta_wool", "Magenta Wool"),
    PINK_WOOL             ("pink_wool", "Pink Wool"),
    WHITE_CONCRETE        ("white_concrete", "White Concrete"),
    LIGHT_GRAY_CONCRETE   ("light_gray_concrete", "Light Gray Concrete"),
    GRAY_CONCRETE         ("gray_concrete", "Gray Concrete"),
    BLACK_CONCRETE        ("black_concrete", "Black Concrete"),
    BROWN_CONCRETE        ("brown_concrete", "Brown Concrete"),
    RED_CONCRETE          ("red_concrete", "Red Concrete"),
    ORANGE_CONCRETE       ("orange_concrete", "Orange Concrete"),
    YELLOW_CONCRETE       ("yellow_concrete", "Yellow Concrete"),
    LIME_CONCRETE         ("lime_concrete", "Lime Concrete"),
    GREEN_CONCRETE        ("green_concrete", "Green Concrete"),
    CYAN_CONCRETE         ("cyan_concrete", "Cyan Concrete"),
    LIGHT_BLUE_CONCRETE   ("light_blue_concrete", "Light Blue Concrete"),
    BLUE_CONCRETE         ("blue_concrete", "Blue Concrete"),
    PURPLE_CONCRETE       ("purple_concrete", "Purple Concrete"),
    MAGENTA_CONCRETE      ("magenta_concrete", "Magenta Concrete"),
    PINK_CONCRETE         ("pink_concrete", "Pink Concrete"),

    WHITE_GLAZED_TERRACOTTA           ("white_glazed_terracotta", "White Glazed Terracotta", true),
    LIGHT_GRAY_GLAZED_TERRACOTTA      ("light_gray_glazed_terracotta", "Light Gray Glazed Terracotta", true),
    GRAY_GLAZED_TERRACOTTA            ("gray_glazed_terracotta", "Gray Glazed Terracotta", true),
    BLACK_GLAZED_TERRACOTTA           ("black_glazed_terracotta", "Black Glazed Terracotta", true),
    BROWN_GLAZED_TERRACOTTA           ("brown_glazed_terracotta", "Brown Glazed Terracotta", true),
    RED_GLAZED_TERRACOTTA             ("red_glazed_terracotta", "Red Glazed Terracotta", true),
    ORANGE_GLAZED_TERRACOTTA          ("orange_glazed_terracotta", "Orange Glazed Terracotta", true),
    YELLOW_GLAZED_TERRACOTTA          ("yellow_glazed_terracotta", "Yellow Glazed Terracotta", true),
    LIME_GLAZED_TERRACOTTA            ("lime_glazed_terracotta", "Lime Glazed Terracotta", true),
    GREEN_GLAZED_TERRACOTTA           ("green_glazed_terracotta", "Green Glazed Terracotta", true),
    CYAN_GLAZED_TERRACOTTA            ("cyan_glazed_terracotta", "Cyan Glazed Terracotta", true),
    LIGHT_BLUE_GLAZED_TERRACOTTA      ("light_blue_glazed_terracotta", "Light Blue Glazed Terracotta", true),
    BLUE_GLAZED_TERRACOTTA            ("blue_glazed_terracotta", "Blue Glazed Terracotta", true),
    PURPLE_GLAZED_TERRACOTTA          ("purple_glazed_terracotta", "Purple Glazed Terracotta", true),
    MAGENTA_GLAZED_TERRACOTTA         ("magenta_glazed_terracotta", "Magenta Glazed Terracotta", true),
    PINK_GLAZED_TERRACOTTA            ("pink_glazed_terracotta", "Pink Glazed Terracotta", true),
    COAL_ORE                          ("coal_ore", "Coal Ore", true),
    DEEPSLATE_COAL_ORE                ("deepslate_coal_ore", "Deepslate Coal Ore", true),
    IRON_ORE                          ("iron_ore", "Iron Ore", true),
    DEEPSLATE_IRON_ORE                ("deepslate_iron_ore", "Deepslate Iron Ore", true),
    COPPER_ORE                        ("copper_ore", "Copper Ore", true),
    DEEPSLATE_COPPER_ORE              ("deepslate_copper_ore", "Deepslate Copper Ore", true),
    GOLD_ORE                          ("gold_ore", "Gold Ore", true),
    DEEPSLATE_GOLD_ORE                ("deepslate_gold_ore", "Deepslate Gold Ore", true),
    REDSTONE_ORE                      ("redstone_ore", "Redstone Ore", true),
    DEEPSLATE_REDSTONE_ORE            ("deepslate_redstone_ore", "Deepslate Redstone Ore", true),
    EMERALD_ORE                       ("emerald_ore", "Emerald Ore", true),
    DEEPSLATE_EMERALD_ORE             ("deepslate_emerald_ore", "Deepslate Emerald Ore", true),
    LAPIS_ORE                         ("lapis_ore", "Lapis Ore", true),
    DEEPSLATE_LAPIS_ORE               ("deepslate_lapis_ore", "Deepslate Lapis Ore", true),
    DIAMOND_ORE                       ("diamond_ore", "Diamond Ore", true),
    DEEPSLATE_DIAMOND_ORE             ("deepslate_diamond_ore", "Deepslate Diamond Ore", true),
    NETHER_GOLD_ORE                   ("nether_gold_ore", "Nether Gold Ore", true),
    NETHER_QUARTZ_ORE                 ("nether_quartz_ore", "Nether Quartz Ore", true),
    ANCIENT_DEBRIS                    ("ancient_debris", "Ancient Debris", true),
    PACKED_ICE                        ("packed_ice", "Packed Ice", true),
    BLUE_ICE                          ("blue_ice", "Blue Ice", true),
    BEDROCK                           ("bedrock", "Bedrock", true),
    REINFORCED_DEEPSLATE              ("reinforced_deepslate", "Reinforced Deepslate", true),
    BOOKSHELF                         ("bookshelf", "Bookshelf", true),
    QUARTZ_PILLAR                     ("quartz_pillar", "Quartz Pillar", true),
    BAMBOO_BLOCK                      ("bamboo_block", "Bamboo Block", true),
    STRIPPED_BAMBOO_BLOCK             ("stripped_bamboo_block", "Stripped Bamboo Block", true),
    BROWN_MUSHROOM_BLOCK              ("brown_mushroom_block", "Brown Mushroom Block", true),
    RED_MUSHROOM_BLOCK                ("red_mushroom_block", "Red Mushroom Block", true),
    MUSHROOM_STEM                     ("mushroom_stem", "Mushroom Stem", true),
    TINTED_GLASS                      ("tinted_glass", "Tinted Glass", true),
    OCHRE_FROGLIGHT                   ("ochre_froglight", "Ochre Froglight", true),
    VERDANT_FROGLIGHT                 ("verdant_froglight", "Verdant Froglight", true),
    PEARLESCENT_FROGLIGHT             ("pearlescent_froglight", "Pearlescent Froglight", true),

    OAK_PLANKS                        ("oak_planks", "Oak Planks", true),
    SPRUCE_PLANKS                     ("spruce_planks", "Spruce Planks", true),
    BIRCH_PLANKS                      ("birch_planks", "Birch Planks", true),
    JUNGLE_PLANKS                     ("jungle_planks", "Jungle Planks", true),
    ACACIA_PLANKS                     ("acacia_planks", "Acacia Planks", true),
    DARK_OAK_PLANKS                   ("dark_oak_planks", "Dark Oak Planks", true),
    MANGROVE_PLANKS                   ("mangrove_planks", "Mangrove Planks", true),
    CHERRY_PLANKS                     ("cherry_planks", "Cherry Planks", true),
    BAMBOO_PLANKS                     ("bamboo_planks", "Bamboo Planks", true),
    CRIMSON_PLANKS                    ("crimson_planks", "Crimson Planks", true),
    WARPED_PLANKS                     ("warped_planks", "Warped Planks", true),
    BAMBOO_MOSAIC                     ("bamboo_mosaic", "Bamboo Mosaic", true),
    OAK_LOG                           ("oak_log", "Oak Log", true),
    SPRUCE_LOG                        ("spruce_log", "Spruce Log", true),
    BIRCH_LOG                         ("birch_log", "Birch Log", true),
    JUNGLE_LOG                        ("jungle_log", "Jungle Log", true),
    ACACIA_LOG                        ("acacia_log", "Acacia Log", true),
    DARK_OAK_LOG                      ("dark_oak_log", "Dark Oak Log", true),
    MANGROVE_LOG                      ("mangrove_log", "Mangrove Log", true),
    CHERRY_LOG                        ("cherry_log", "Cherry Log", true),
    CRIMSON_STEM                      ("crimson_stem", "Crimson Stem", true),
    WARPED_STEM                       ("warped_stem", "Warped Stem", true),
    STRIPPED_OAK_LOG                  ("stripped_oak_log", "Stripped Oak Log", true),
    STRIPPED_SPRUCE_LOG               ("stripped_spruce_log", "Stripped Spruce Log", true),
    STRIPPED_BIRCH_LOG                ("stripped_birch_log", "Stripped Birch Log", true),
    STRIPPED_JUNGLE_LOG               ("stripped_jungle_log", "Stripped Jungle Log", true),
    STRIPPED_ACACIA_LOG               ("stripped_acacia_log", "Stripped Acacia Log", true),
    STRIPPED_DARK_OAK_LOG             ("stripped_dark_oak_log", "Stripped Dark Oak Log", true),
    STRIPPED_MANGROVE_LOG             ("stripped_mangrove_log", "Stripped Mangrove Log", true),
    STRIPPED_CHERRY_LOG               ("stripped_cherry_log", "Stripped Cherry Log", true),
    STRIPPED_CRIMSON_STEM             ("stripped_crimson_stem", "Stripped Crimson Stem", true),
    STRIPPED_WARPED_STEM              ("stripped_warped_stem", "Stripped Warped Stem", true),
    COBBLESTONE                       ("cobblestone", "Cobblestone", true),
    MOSSY_COBBLESTONE                 ("mossy_cobblestone", "Mossy Cobblestone", true),
    SMOOTH_STONE                      ("smooth_stone", "Smooth Stone", true),
    STONE_BRICKS                      ("stone_bricks", "Stone Bricks", true),
    MOSSY_STONE_BRICKS                ("mossy_stone_bricks", "Mossy Stone Bricks", true),
    CRACKED_STONE_BRICKS              ("cracked_stone_bricks", "Cracked Stone Bricks", true),
    CHISELED_STONE_BRICKS             ("chiseled_stone_bricks", "Chiseled Stone Bricks", true),
    POLISHED_GRANITE                  ("polished_granite", "Polished Granite", true),
    POLISHED_DIORITE                  ("polished_diorite", "Polished Diorite", true),
    POLISHED_ANDESITE                 ("polished_andesite", "Polished Andesite", true),
    COBBLED_DEEPSLATE                 ("cobbled_deepslate", "Cobbled Deepslate", true),
    POLISHED_DEEPSLATE                ("polished_deepslate", "Polished Deepslate", true),
    DEEPSLATE_BRICKS                  ("deepslate_bricks", "Deepslate Bricks", true),
    CRACKED_DEEPSLATE_BRICKS          ("cracked_deepslate_bricks", "Cracked Deepslate Bricks", true),
    DEEPSLATE_TILES                   ("deepslate_tiles", "Deepslate Tiles", true),
    CRACKED_DEEPSLATE_TILES           ("cracked_deepslate_tiles", "Cracked Deepslate Tiles", true),
    CHISELED_DEEPSLATE                ("chiseled_deepslate", "Chiseled Deepslate", true),
    TUFF                              ("tuff", "Tuff", true),
    POLISHED_TUFF                     ("polished_tuff", "Polished Tuff", true),
    TUFF_BRICKS                       ("tuff_bricks", "Tuff Bricks", true),
    CHISELED_TUFF                     ("chiseled_tuff", "Chiseled Tuff", true),
    CALCITE                           ("calcite", "Calcite", true),
    DRIPSTONE_BLOCK                   ("dripstone_block", "Dripstone Block", true),
    BLACKSTONE                        ("blackstone", "Blackstone", true),
    POLISHED_BLACKSTONE               ("polished_blackstone", "Polished Blackstone", true),
    POLISHED_BLACKSTONE_BRICKS        ("polished_blackstone_bricks", "Polished Blackstone Bricks", true),
    CRACKED_POLISHED_BLACKSTONE_BRICKS("cracked_polished_blackstone_bricks", "Cracked Polished Blackstone Bricks", true),
    CHISELED_POLISHED_BLACKSTONE      ("chiseled_polished_blackstone", "Chiseled Polished Blackstone", true),
    GILDED_BLACKSTONE                 ("gilded_blackstone", "Gilded Blackstone", true),
    NETHERRACK                        ("netherrack", "Netherrack", true),
    NETHER_BRICKS                     ("nether_bricks", "Nether Bricks", true),
    RED_NETHER_BRICKS                 ("red_nether_bricks", "Red Nether Bricks", true),
    CRACKED_NETHER_BRICKS             ("cracked_nether_bricks", "Cracked Nether Bricks", true),
    CHISELED_NETHER_BRICKS            ("chiseled_nether_bricks", "Chiseled Nether Bricks", true),
    BASALT                            ("basalt", "Basalt", true),
    POLISHED_BASALT                   ("polished_basalt", "Polished Basalt", true),
    SMOOTH_BASALT                     ("smooth_basalt", "Smooth Basalt", true),
    END_STONE                         ("end_stone", "End Stone", true),
    END_STONE_BRICKS                  ("end_stone_bricks", "End Stone Bricks", true),
    PURPUR_BLOCK                      ("purpur_block", "Purpur Block", true),
    PURPUR_PILLAR                     ("purpur_pillar", "Purpur Pillar", true),
    OBSIDIAN                          ("obsidian", "Obsidian", true),
    CRYING_OBSIDIAN                   ("crying_obsidian", "Crying Obsidian", true),
    MAGMA                             ("magma", "Magma", true),
    GLOWSTONE                         ("glowstone", "Glowstone", true),
    SEA_LANTERN                       ("sea_lantern", "Sea Lantern", true),
    SHROOMLIGHT                       ("shroomlight", "Shroomlight", true),
    QUARTZ_BLOCK                      ("quartz_block", "Quartz Block", true),
    QUARTZ_BRICKS                     ("quartz_bricks", "Quartz Bricks", true),
    CHISELED_QUARTZ_BLOCK             ("chiseled_quartz_block", "Chiseled Quartz Block", true),
    BRICKS                            ("bricks", "Bricks", true),
    MUD_BRICKS                        ("mud_bricks", "Mud Bricks", true),
    PACKED_MUD                        ("packed_mud", "Packed Mud", true),
    MUD                               ("mud", "Mud", true),
    PRISMARINE                        ("prismarine", "Prismarine", true),
    PRISMARINE_BRICKS                 ("prismarine_bricks", "Prismarine Bricks", true),
    DARK_PRISMARINE                   ("dark_prismarine", "Dark Prismarine", true),
    SANDSTONE                         ("sandstone", "Sandstone", true),
    CHISELED_SANDSTONE                ("chiseled_sandstone", "Chiseled Sandstone", true),
    CUT_SANDSTONE                     ("cut_sandstone", "Cut Sandstone", true),
    RED_SANDSTONE                     ("red_sandstone", "Red Sandstone", true),
    CHISELED_RED_SANDSTONE            ("chiseled_red_sandstone", "Chiseled Red Sandstone", true),
    CUT_RED_SANDSTONE                 ("cut_red_sandstone", "Cut Red Sandstone", true),
    AMETHYST_BLOCK                    ("amethyst_block", "Amethyst Block", true),
    BUDDING_AMETHYST                  ("budding_amethyst", "Budding Amethyst", true),
    SCULK                             ("sculk", "Sculk", true),
    BONE_BLOCK                        ("bone_block", "Bone Block", true),
    DIRT                              ("dirt", "Dirt", true),
    COARSE_DIRT                       ("coarse_dirt", "Coarse Dirt", true),
    ROOTED_DIRT                       ("rooted_dirt", "Rooted Dirt", true),
    CLAY                              ("clay", "Clay", true),
    GRAVEL                            ("gravel", "Gravel", true),
    SAND                              ("sand", "Sand", true),
    RED_SAND                          ("red_sand", "Red Sand", true),
    MOSS_BLOCK                        ("moss_block", "Moss Block", true),
    MYCELIUM                          ("mycelium", "Mycelium", true),
    SOUL_SAND                         ("soul_sand", "Soul Sand", true),
    SOUL_SOIL                         ("soul_soil", "Soul Soil", true),
    HAY_BLOCK                         ("hay_block", "Hay Block", true),
    SPONGE                            ("sponge", "Sponge", true),
    WET_SPONGE                        ("wet_sponge", "Wet Sponge", true),
    SLIME_BLOCK                       ("slime_block", "Slime Block", true),
    HONEY_BLOCK                       ("honey_block", "Honey Block", true),
    HONEYCOMB_BLOCK                   ("honeycomb_block", "Honeycomb Block", true),
    MELON                             ("melon", "Melon", true),
    NETHER_WART_BLOCK                 ("nether_wart_block", "Nether Wart Block", true),
    WARPED_WART_BLOCK                 ("warped_wart_block", "Warped Wart Block", true),
    IRON_BLOCK                        ("iron_block", "Iron Block", true),
    GOLD_BLOCK                        ("gold_block", "Gold Block", true),
    DIAMOND_BLOCK                     ("diamond_block", "Diamond Block", true),
    EMERALD_BLOCK                     ("emerald_block", "Emerald Block", true),
    LAPIS_BLOCK                       ("lapis_block", "Lapis Block", true),
    REDSTONE_BLOCK                    ("redstone_block", "Redstone Block", true),
    COAL_BLOCK                        ("coal_block", "Coal Block", true),
    NETHERITE_BLOCK                   ("netherite_block", "Netherite Block", true),
    RAW_IRON_BLOCK                    ("raw_iron_block", "Raw Iron Block", true),
    RAW_COPPER_BLOCK                  ("raw_copper_block", "Raw Copper Block", true),
    RAW_GOLD_BLOCK                    ("raw_gold_block", "Raw Gold Block", true),
    COPPER_BLOCK                      ("copper_block", "Copper Block", true),
    EXPOSED_COPPER                    ("exposed_copper", "Exposed Copper", true),
    WEATHERED_COPPER                  ("weathered_copper", "Weathered Copper", true),
    OXIDIZED_COPPER                   ("oxidized_copper", "Oxidized Copper", true),
    CUT_COPPER                        ("cut_copper", "Cut Copper", true),
    EXPOSED_CUT_COPPER                ("exposed_cut_copper", "Exposed Cut Copper", true),
    WEATHERED_CUT_COPPER              ("weathered_cut_copper", "Weathered Cut Copper", true),
    OXIDIZED_CUT_COPPER               ("oxidized_cut_copper", "Oxidized Cut Copper", true),
    CHISELED_COPPER                   ("chiseled_copper", "Chiseled Copper", true),
    COPPER_GRATE                      ("copper_grate", "Copper Grate", true),
    WHITE_CONCRETE_POWDER             ("white_concrete_powder", "White Concrete Powder", true),
    LIGHT_GRAY_CONCRETE_POWDER        ("light_gray_concrete_powder", "Light Gray Concrete Powder", true),
    GRAY_CONCRETE_POWDER              ("gray_concrete_powder", "Gray Concrete Powder", true),
    BLACK_CONCRETE_POWDER             ("black_concrete_powder", "Black Concrete Powder", true),
    BROWN_CONCRETE_POWDER             ("brown_concrete_powder", "Brown Concrete Powder", true),
    RED_CONCRETE_POWDER               ("red_concrete_powder", "Red Concrete Powder", true),
    ORANGE_CONCRETE_POWDER            ("orange_concrete_powder", "Orange Concrete Powder", true),
    YELLOW_CONCRETE_POWDER            ("yellow_concrete_powder", "Yellow Concrete Powder", true),
    LIME_CONCRETE_POWDER              ("lime_concrete_powder", "Lime Concrete Powder", true),
    GREEN_CONCRETE_POWDER             ("green_concrete_powder", "Green Concrete Powder", true),
    CYAN_CONCRETE_POWDER              ("cyan_concrete_powder", "Cyan Concrete Powder", true),
    LIGHT_BLUE_CONCRETE_POWDER        ("light_blue_concrete_powder", "Light Blue Concrete Powder", true),
    BLUE_CONCRETE_POWDER              ("blue_concrete_powder", "Blue Concrete Powder", true),
    PURPLE_CONCRETE_POWDER            ("purple_concrete_powder", "Purple Concrete Powder", true),
    MAGENTA_CONCRETE_POWDER           ("magenta_concrete_powder", "Magenta Concrete Powder", true),
    PINK_CONCRETE_POWDER              ("pink_concrete_powder", "Pink Concrete Powder", true),
    TERRACOTTA                        ("terracotta", "Terracotta", true),
    WHITE_TERRACOTTA                  ("white_terracotta", "White Terracotta", true),
    LIGHT_GRAY_TERRACOTTA             ("light_gray_terracotta", "Light Gray Terracotta", true),
    GRAY_TERRACOTTA                   ("gray_terracotta", "Gray Terracotta", true),
    BLACK_TERRACOTTA                  ("black_terracotta", "Black Terracotta", true),
    BROWN_TERRACOTTA                  ("brown_terracotta", "Brown Terracotta", true),
    RED_TERRACOTTA                    ("red_terracotta", "Red Terracotta", true),
    ORANGE_TERRACOTTA                 ("orange_terracotta", "Orange Terracotta", true),
    YELLOW_TERRACOTTA                 ("yellow_terracotta", "Yellow Terracotta", true),
    LIME_TERRACOTTA                   ("lime_terracotta", "Lime Terracotta", true),
    GREEN_TERRACOTTA                  ("green_terracotta", "Green Terracotta", true),
    CYAN_TERRACOTTA                   ("cyan_terracotta", "Cyan Terracotta", true),
    LIGHT_BLUE_TERRACOTTA             ("light_blue_terracotta", "Light Blue Terracotta", true),
    BLUE_TERRACOTTA                   ("blue_terracotta", "Blue Terracotta", true),
    PURPLE_TERRACOTTA                 ("purple_terracotta", "Purple Terracotta", true),
    MAGENTA_TERRACOTTA                ("magenta_terracotta", "Magenta Terracotta", true),
    PINK_TERRACOTTA                   ("pink_terracotta", "Pink Terracotta", true);

    private final String name;
    private static java.util.Map<String, TrackVariant> byBlock;

    public static TrackVariant forBlock(String blockPath) {
        if (byBlock == null) {
            java.util.Map<String, TrackVariant> map = new java.util.HashMap<>();
            for (TrackVariant v : values()) {
                map.put(v.materialName(), v);
            }
            byBlock = map;
        }
        return byBlock.get(blockPath);
    }

    private final String display;
    private final boolean copycat;

    TrackVariant(String name, String display) {
        this(name, display, false);
    }

    TrackVariant(String name, String display, boolean copycat) {
        this.name = name;
        this.display = display;
        this.copycat = copycat;
    }

    public boolean isCopycat() {
        return copycat;
    }

    public String trackName() {
        return name + "_track";
    }

    public String blockName() {
        return name + "_track_material";
    }

    public String materialName() {
        return name;
    }

    public String displayName() {
        return display + " Coaster Track";
    }
}
